# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hort < Formula
  desc "Local secret and config store for humans and AI agents"
  homepage "https://github.com/sebastian-breitzke/hort"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sebastian-breitzke/hort/releases/download/v0.2.2/hort_0.2.2_darwin_amd64.tar.gz"
      sha256 "1386c424aa9dfb5ec12f747bb35a6fbe765d874caaeeb3c6bbd53a8e7c4ada1d"

      define_method(:install) do
        bin.install "hort"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sebastian-breitzke/hort/releases/download/v0.2.2/hort_0.2.2_darwin_arm64.tar.gz"
      sha256 "6edd25fc661fdb1bf4be63c31bbf180f6554d499ca34df906dae38ffd5409fba"

      define_method(:install) do
        bin.install "hort"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sebastian-breitzke/hort/releases/download/v0.2.2/hort_0.2.2_linux_amd64.tar.gz"
      sha256 "a4780bd3f6d3a8fc5381381f1974b456dc357b61e55c6f04211342eaae5914dd"
      define_method(:install) do
        bin.install "hort"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sebastian-breitzke/hort/releases/download/v0.2.2/hort_0.2.2_linux_arm64.tar.gz"
      sha256 "c61bec08c70a064849370a9e9c14907e4c69d56a5e4db97a78f14f043e3b7c80"
      define_method(:install) do
        bin.install "hort"
      end
    end
  end

  test do
    assert_match "hort", shell_output("#{bin}/hort --help")
  end
end
