# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hort < Formula
  desc "Local secret and config store for humans and AI agents"
  homepage "https://github.com/sebastian-breitzke/hort"
  version "0.2.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sebastian-breitzke/hort/releases/download/v0.2.4/hort_0.2.4_darwin_amd64.tar.gz"
      sha256 "4099c2a9276a5558af69ef86a523acf1127ee704e09af2749b17488e17c7b9f0"

      define_method(:install) do
        bin.install "hort"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sebastian-breitzke/hort/releases/download/v0.2.4/hort_0.2.4_darwin_arm64.tar.gz"
      sha256 "5823c9282c95c05aa091a9e7c7caf32b8f91428b0917017996e3cfdfe859011d"

      define_method(:install) do
        bin.install "hort"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sebastian-breitzke/hort/releases/download/v0.2.4/hort_0.2.4_linux_amd64.tar.gz"
      sha256 "c8df1826776edf372417e231148f88dace603fbef9ca4e2d4dc789854cc67f49"
      define_method(:install) do
        bin.install "hort"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sebastian-breitzke/hort/releases/download/v0.2.4/hort_0.2.4_linux_arm64.tar.gz"
      sha256 "890de78a3858d2b7fe434b861343a8f2d2d8fff0fc5cb12fc349503ee3f7cac7"
      define_method(:install) do
        bin.install "hort"
      end
    end
  end

  test do
    assert_match "hort", shell_output("#{bin}/hort --help")
  end
end
