# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hort < Formula
  desc "Local secret and config store for humans and AI agents"
  homepage "https://github.com/sebastian-breitzke/hort"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sebastian-breitzke/hort/releases/download/v0.2.0/hort_0.2.0_darwin_amd64.tar.gz"
      sha256 "c0d5e663992a874ab5e768a269fc447d2ad40e8d4c3777a20ae858277250d159"

      define_method(:install) do
        bin.install "hort"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sebastian-breitzke/hort/releases/download/v0.2.0/hort_0.2.0_darwin_arm64.tar.gz"
      sha256 "c87c1d610756f18bc98cdfb15dac1c284854c066e0261a631a2b2073ed2d3ac8"

      define_method(:install) do
        bin.install "hort"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sebastian-breitzke/hort/releases/download/v0.2.0/hort_0.2.0_linux_amd64.tar.gz"
      sha256 "8796132fa75b1fda3345d64ecec947bd58ebe506bef2a65f4e62d83ff1c0dbcc"
      define_method(:install) do
        bin.install "hort"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sebastian-breitzke/hort/releases/download/v0.2.0/hort_0.2.0_linux_arm64.tar.gz"
      sha256 "de60205bb548b7918af5c80870ce96cfed9439eda349f4d50a3ccc7d449931b6"
      define_method(:install) do
        bin.install "hort"
      end
    end
  end

  test do
    assert_match "hort", shell_output("#{bin}/hort --help")
  end
end
